services:
  meson-compute:
    build: .
    ports:
      - 7777:7777
    volumes:
      - .env:/app/.env
    entrypoint: /bin/sh -c "uvicorn main_compute:app --host 0.0.0.0 --port 7777 --reload --workers 1"
    restart: always
    networks:
      - meson-network
  meson-storage:
    build: .
    ports:
      - 7772:7772
    volumes:
      - .env:/app/.env
    entrypoint: /bin/sh -c "uvicorn main_storage:app --host 0.0.0.0 --port 7772 --reload --workers 1"
    restart: always
    networks:
      - meson-network
  meson-services:
    build: .
    ports:
      - 7770:7770
    volumes:
      - .env:/app/.env
    entrypoint: /bin/sh -c "uvicorn main_service:app --host 0.0.0.0 --port 7770 --reload --workers 1"
    restart: always
    networks:
      - meson-network

networks:
  meson-network:
    external: true