services:
  compute:
    build: .
    image: ${IMAGE_NAME:-elemento-meson-template-compute:local}
    environment:
      - PYTHONPATH=/app:/app/elemento_billing_manager
    ports:
      - 7777:7777
    volumes:
      - .env:/app/.env
      - ./certs:/certs:ro 
    entrypoint: /bin/sh -c "uvicorn main_compute:app --host 0.0.0.0 --port 7777 --reload --workers 1 --ssl-keyfile '/certs/tls.key' --ssl-certfile '/certs/tls.crt'"
    restart: always

  storage:
    build: .
    image: ${IMAGE_NAME:-elemento-meson-template-storage:local}
    environment:
      - PYTHONPATH=/app:/app/elemento_billing_manager
    ports:
      - 7772:7772
    volumes:
      - .env:/app/.env
      - ./certs:/certs:ro 
    entrypoint: /bin/sh -c "uvicorn main_storage:app --host 0.0.0.0 --port 7772 --reload --workers 1 --ssl-keyfile '/certs/tls.key' --ssl-certfile '/certs/tls.crt'"
    restart: always

  service:
    build: .
    image: ${IMAGE_NAME:-elemento-meson-template-service:local}
    environment:
      - PYTHONPATH=/app:/app/elemento_billing_manager
    ports:
      - 7770:7770
    volumes:
      - .env:/app/.env
      - ./certs:/certs:ro 
    entrypoint: /bin/sh -c "uvicorn main_service:app --host 0.0.0.0 --port 7770 --reload --workers 1 --ssl-keyfile '/certs/tls.key' --ssl-certfile '/certs/tls.crt'"
    restart: always